import { Product } from "@/types";

export const products: Product[] = [
  // Preventiva (4)
  {
    id: "prev-001",
    nameEs: "Pasta Profil\u00e1ctica con Fl\u00faor",
    nameEn: "Fluoride Prophy Paste",
    descriptionEs: "Pasta profil\u00e1ctica con fl\u00faor para limpieza profesional. Grano medio, sabor menta.",
    descriptionEn: "Fluoride prophy paste for professional cleaning. Medium grit, mint flavor.",
    category: "preventiva",
    image: "/products/prev-001.jpg",
    featured: true,
    tags: ["profilaxis", "fl\u00faor", "prevenci\u00f3n"],
  },
  {
    id: "prev-002",
    nameEs: "Sellante de Fosas y Fisuras Fotocurable",
    nameEn: "Light-Cure Pit and Fissure Sealant",
    descriptionEs: "Sellante fotocurable de baja viscosidad para prevenci\u00f3n de caries en molares.",
    descriptionEn: "Low-viscosity light-cure sealant for molar caries prevention.",
    category: "preventiva",
    image: "/products/prev-002.jpg",
    featured: false,
    tags: ["sellante", "prevenci\u00f3n"],
  },
  {
    id: "prev-003",
    nameEs: "Barniz de Fl\u00faor al 5%",
    nameEn: "5% Fluoride Varnish",
    descriptionEs: "Barniz de fluoruro de sodio al 5% para aplicaci\u00f3n profesional. Tubo de 10ml.",
    descriptionEn: "5% sodium fluoride varnish for professional application. 10ml tube.",
    category: "preventiva",
    image: "/products/prev-003.jpg",
    featured: false,
    tags: ["fl\u00faor", "barniz"],
  },
  {
    id: "prev-004",
    nameEs: "Kit de Profilaxis Completo",
    nameEn: "Complete Prophylaxis Kit",
    descriptionEs: "Kit con cepillos, copas de goma, pasta profil\u00e1ctica y porta\u00e1ngulo desechable.",
    descriptionEn: "Kit with brushes, rubber cups, prophy paste and disposable prophy angle.",
    category: "preventiva",
    image: "/products/prev-004.jpg",
    featured: false,
    tags: ["profilaxis", "kit"],
  },

  // Restaurativa (4)
  {
    id: "rest-001",
    nameEs: "Kit de Resina Compuesta A2",
    nameEn: "Composite Resin Kit A2",
    descriptionEs: "Resina compuesta nanoh\u00edbrida color A2. Excelente pulido y resistencia. Jeringa de 4g.",
    descriptionEn: "Nanohybrid composite resin shade A2. Excellent polish and resistance. 4g syringe.",
    category: "restaurativa",
    image: "/products/rest-001.jpg",
    featured: true,
    tags: ["resina", "restauraci\u00f3n"],
  },
  {
    id: "rest-002",
    nameEs: "Cemento de Ion\u00f3mero de Vidrio",
    nameEn: "Glass Ionomer Cement",
    descriptionEs: "Cemento de ion\u00f3mero de vidrio para cementaci\u00f3n y restauraciones. Liberaci\u00f3n de fl\u00faor.",
    descriptionEn: "Glass ionomer cement for cementation and restorations. Fluoride release.",
    category: "restaurativa",
    image: "/products/rest-002.jpg",
    featured: false,
    tags: ["cemento", "ion\u00f3mero"],
  },
  {
    id: "rest-003",
    nameEs: "Adhesivo Dental Universal",
    nameEn: "Universal Dental Adhesive",
    descriptionEs: "Sistema adhesivo universal de quinta generaci\u00f3n. Compatible con todas las resinas.",
    descriptionEn: "Fifth generation universal adhesive system. Compatible with all resins.",
    category: "restaurativa",
    image: "/products/rest-003.jpg",
    featured: false,
    tags: ["adhesivo", "bonding"],
  },
  {
    id: "rest-004",
    nameEs: "\u00c1cido Grabador al 37%",
    nameEn: "37% Etching Acid",
    descriptionEs: "Gel de \u00e1cido fosf\u00f3rico al 37% para grabado de esmalte y dentina. Jeringa de 5ml.",
    descriptionEn: "37% phosphoric acid gel for enamel and dentin etching. 5ml syringe.",
    category: "restaurativa",
    image: "/products/rest-004.jpg",
    featured: false,
    tags: ["\u00e1cido", "grabado"],
  },

  // Endodoncia (4)
  {
    id: "endo-001",
    nameEs: "Limas Endod\u00f3nticas Rotatorias NiTi",
    nameEn: "NiTi Rotary Endodontic Files",
    descriptionEs: "Limas rotatorias de n\u00edquel-titanio para instrumentaci\u00f3n de conductos. Set de 6 unidades.",
    descriptionEn: "Nickel-titanium rotary files for root canal instrumentation. Set of 6.",
    category: "endodoncia",
    image: "/products/endo-001.jpg",
    featured: true,
    tags: ["limas", "endodoncia", "NiTi"],
  },
  {
    id: "endo-002",
    nameEs: "Conos de Gutapercha Estandarizados",
    nameEn: "Standardized Gutta-Percha Points",
    descriptionEs: "Conos de gutapercha estandarizados para obturaci\u00f3n de conductos. Caja de 120 unidades.",
    descriptionEn: "Standardized gutta-percha points for root canal obturation. Box of 120.",
    category: "endodoncia",
    image: "/products/endo-002.jpg",
    featured: false,
    tags: ["gutapercha", "obturaci\u00f3n"],
  },
  {
    id: "endo-003",
    nameEs: "Sellador de Conductos a Base de Resina",
    nameEn: "Resin-Based Root Canal Sealer",
    descriptionEs: "Sellador endod\u00f3ntico a base de resina ep\u00f3xica. Excelente sellado y radioopacidad.",
    descriptionEn: "Epoxy resin-based endodontic sealer. Excellent seal and radiopacity.",
    category: "endodoncia",
    image: "/products/endo-003.jpg",
    featured: false,
    tags: ["sellador", "conductos"],
  },
  {
    id: "endo-004",
    nameEs: "Localizador de \u00c1pice Digital",
    nameEn: "Digital Apex Locator",
    descriptionEs: "Localizador electr\u00f3nico de \u00e1pice con pantalla LCD a color. Alta precisi\u00f3n.",
    descriptionEn: "Electronic apex locator with color LCD display. High precision.",
    category: "endodoncia",
    image: "/products/endo-004.jpg",
    featured: false,
    tags: ["localizador", "\u00e1pice"],
  },

  // Ortodoncia (4)
  {
    id: "orto-001",
    nameEs: "Kit de Brackets Met\u00e1licos MBT",
    nameEn: "MBT Metal Bracket Kit",
    descriptionEs: "Kit de brackets met\u00e1licos prescripci\u00f3n MBT .022. Set de 20 brackets con malla.",
    descriptionEn: "MBT prescription metal bracket kit .022. Set of 20 brackets with mesh base.",
    category: "ortodoncia",
    image: "/products/orto-001.jpg",
    featured: true,
    tags: ["brackets", "ortodoncia"],
  },
  {
    id: "orto-002",
    nameEs: "Alambre de Ortodoncia NiTi Redondo",
    nameEn: "Round NiTi Orthodontic Wire",
    descriptionEs: "Alambre superel\u00e1stico de NiTi redondo .016. Paquete de 10 arcos superiores.",
    descriptionEn: "Superelastic round NiTi wire .016. Pack of 10 upper arches.",
    category: "ortodoncia",
    image: "/products/orto-002.jpg",
    featured: false,
    tags: ["alambre", "NiTi"],
  },
  {
    id: "orto-003",
    nameEs: "El\u00e1sticos Intraorales Surtidos",
    nameEn: "Assorted Intraoral Elastics",
    descriptionEs: "El\u00e1sticos de l\u00e1tex intraorales en diferentes fuerzas y di\u00e1metros. Bolsa de 100.",
    descriptionEn: "Latex intraoral elastics in various forces and diameters. Bag of 100.",
    category: "ortodoncia",
    image: "/products/orto-003.jpg",
    featured: false,
    tags: ["el\u00e1sticos", "ortodoncia"],
  },
  {
    id: "orto-004",
    nameEs: "Cera de Ortodoncia para Pacientes",
    nameEn: "Orthodontic Wax for Patients",
    descriptionEs: "Cera protectora para brackets. Sin sabor, hipoalerg\u00e9nica. Caja de 50 estuches.",
    descriptionEn: "Protective wax for brackets. Unflavored, hypoallergenic. Box of 50 cases.",
    category: "ortodoncia",
    image: "/products/orto-004.jpg",
    featured: false,
    tags: ["cera", "protector"],
  },

  // Cirugia Oral (4)
  {
    id: "cir-001",
    nameEs: "F\u00f3rceps Universal Superior #150",
    nameEn: "Universal Upper Forceps #150",
    descriptionEs: "F\u00f3rceps universal para premolares y ra\u00edces superiores. Acero quir\u00fargico de alta calidad.",
    descriptionEn: "Universal forceps for upper premolars and roots. High-quality surgical steel.",
    category: "cirugia",
    image: "/products/cir-001.jpg",
    featured: true,
    tags: ["f\u00f3rceps", "cirug\u00eda"],
  },
  {
    id: "cir-002",
    nameEs: "Kit de Suturas Absorbibles 4-0",
    nameEn: "Absorbable Suture Kit 4-0",
    descriptionEs: "Suturas absorbibles de \u00e1cido poliglic\u00f3lico 4-0 con aguja curva. Caja de 12.",
    descriptionEn: "Polyglycolic acid absorbable sutures 4-0 with curved needle. Box of 12.",
    category: "cirugia",
    image: "/products/cir-002.jpg",
    featured: false,
    tags: ["suturas", "cirug\u00eda"],
  },
  {
    id: "cir-003",
    nameEs: "Elevador Recto #301",
    nameEn: "Straight Elevator #301",
    descriptionEs: "Elevador recto de acero inoxidable para exodoncia. Mango ergon\u00f3mico antideslizante.",
    descriptionEn: "Stainless steel straight elevator for extractions. Non-slip ergonomic handle.",
    category: "cirugia",
    image: "/products/cir-003.jpg",
    featured: false,
    tags: ["elevador", "exodoncia"],
  },
  {
    id: "cir-004",
    nameEs: "Mango de Bistur\u00ed #3 con Hojas",
    nameEn: "Scalpel Handle #3 with Blades",
    descriptionEs: "Mango de bistur\u00ed #3 de acero inoxidable con 10 hojas #15 est\u00e9riles.",
    descriptionEn: "Stainless steel #3 scalpel handle with 10 sterile #15 blades.",
    category: "cirugia",
    image: "/products/cir-004.jpg",
    featured: false,
    tags: ["bistur\u00ed", "cirug\u00eda"],
  },

  // Periodoncia (4)
  {
    id: "perio-001",
    nameEs: "Kit de Curetas Gracey (7 piezas)",
    nameEn: "Gracey Curette Kit (7 pieces)",
    descriptionEs: "Set completo de curetas Gracey para raspado y alisado radicular. Acero quir\u00fargico.",
    descriptionEn: "Complete Gracey curette set for scaling and root planing. Surgical steel.",
    category: "periodoncia",
    image: "/products/perio-001.jpg",
    featured: true,
    tags: ["cureta", "periodoncia"],
  },
  {
    id: "perio-002",
    nameEs: "Sonda Periodontal Williams",
    nameEn: "Williams Periodontal Probe",
    descriptionEs: "Sonda periodontal Williams con marcas a 1-2-3-5-7-8-9-10mm. Acero inoxidable.",
    descriptionEn: "Williams periodontal probe marked at 1-2-3-5-7-8-9-10mm. Stainless steel.",
    category: "periodoncia",
    image: "/products/perio-002.jpg",
    featured: false,
    tags: ["sonda", "diagn\u00f3stico"],
  },
  {
    id: "perio-003",
    nameEs: "Scaler Ultrason\u00edco con Puntas",
    nameEn: "Ultrasonic Scaler with Tips",
    descriptionEs: "Scaler ultras\u00f3nico de mesa con 5 puntas intercambiables. Ideal para profilaxis.",
    descriptionEn: "Tabletop ultrasonic scaler with 5 interchangeable tips. Ideal for prophylaxis.",
    category: "periodoncia",
    image: "/products/perio-003.jpg",
    featured: false,
    tags: ["scaler", "ultrasonido"],
  },
  {
    id: "perio-004",
    nameEs: "Puntas de Scaler Universales (set de 5)",
    nameEn: "Universal Scaler Tips (set of 5)",
    descriptionEs: "Puntas de repuesto universales compatibles con scalers piezoel\u00e9ctricos.",
    descriptionEn: "Universal replacement tips compatible with piezoelectric scalers.",
    category: "periodoncia",
    image: "/products/perio-004.jpg",
    featured: false,
    tags: ["puntas", "scaler"],
  },

  // Control de Infecciones (4)
  {
    id: "inf-001",
    nameEs: "Caja de Guantes de Nitrilo x100",
    nameEn: "Nitrile Gloves Box x100",
    descriptionEs: "Guantes de nitrilo sin polvo, talla M. Caja de 100 unidades. Hipoalerg\u00e9nicos.",
    descriptionEn: "Powder-free nitrile gloves, size M. Box of 100 units. Hypoallergenic.",
    category: "control-infecciones",
    image: "/products/inf-001.jpg",
    featured: true,
    tags: ["guantes", "nitrilo"],
  },
  {
    id: "inf-002",
    nameEs: "Tapabocas Quir\u00fargico x50",
    nameEn: "Surgical Face Masks x50",
    descriptionEs: "Tapabocas quir\u00fargicos de 3 capas con el\u00e1stico. Caja de 50 unidades.",
    descriptionEn: "3-ply surgical face masks with elastic. Box of 50 units.",
    category: "control-infecciones",
    image: "/products/inf-002.jpg",
    featured: false,
    tags: ["tapabocas", "bioseguridad"],
  },
  {
    id: "inf-003",
    nameEs: "Desinfectante de Superficies 1L",
    nameEn: "Surface Disinfectant 1L",
    descriptionEs: "Desinfectante de superficies de nivel intermedio. Acci\u00f3n bactericida y viricida.",
    descriptionEn: "Intermediate-level surface disinfectant. Bactericidal and viricidal action.",
    category: "control-infecciones",
    image: "/products/inf-003.jpg",
    featured: false,
    tags: ["desinfectante", "limpieza"],
  },
  {
    id: "inf-004",
    nameEs: "Bolsas de Esterilizaci\u00f3n x200",
    nameEn: "Sterilization Pouches x200",
    descriptionEs: "Bolsas autoadhesivas para esterilizaci\u00f3n en autoclave. Indicador qu\u00edmico integrado.",
    descriptionEn: "Self-sealing sterilization pouches for autoclave. Integrated chemical indicator.",
    category: "control-infecciones",
    image: "/products/inf-004.jpg",
    featured: false,
    tags: ["esterilizaci\u00f3n", "bolsas"],
  },

  // Equipos y Tecnologia (4)
  {
    id: "equip-001",
    nameEs: "Unidad Dental Hidr\u00e1ulica Premium",
    nameEn: "Premium Hydraulic Dental Unit",
    descriptionEs: "Unidad dental hidr\u00e1ulica completa con sill\u00f3n, l\u00e1mpara, bandeja y escupidera.",
    descriptionEn: "Complete hydraulic dental unit with chair, lamp, tray and cuspidor.",
    category: "equipos",
    image: "/products/equip-001.jpg",
    featured: true,
    tags: ["unidad", "sill\u00f3n"],
  },
  {
    id: "equip-002",
    nameEs: "L\u00e1mpara de Fotocurado LED",
    nameEn: "LED Curing Light",
    descriptionEs: "L\u00e1mpara de fotocurado LED inal\u00e1mbrica. 1200mW/cm\u00b2, bater\u00eda de larga duraci\u00f3n.",
    descriptionEn: "Wireless LED curing light. 1200mW/cm\u00b2, long-lasting battery.",
    category: "equipos",
    image: "/products/equip-002.jpg",
    featured: false,
    tags: ["l\u00e1mpara", "fotocurado"],
  },
  {
    id: "equip-003",
    nameEs: "Autoclave Digital 18 Litros",
    nameEn: "18-Liter Digital Autoclave",
    descriptionEs: "Autoclave digital clase B de 18 litros. Ciclos autom\u00e1ticos, pantalla LCD.",
    descriptionEn: "18-liter class B digital autoclave. Automatic cycles, LCD display.",
    category: "equipos",
    image: "/products/equip-003.jpg",
    featured: false,
    tags: ["autoclave", "esterilizaci\u00f3n"],
  },
  {
    id: "equip-004",
    nameEs: "Pieza de Mano de Alta Velocidad",
    nameEn: "High-Speed Handpiece",
    descriptionEs: "Pieza de mano de alta velocidad con cabeza est\u00e1ndar. Iluminaci\u00f3n LED integrada.",
    descriptionEn: "High-speed handpiece with standard head. Integrated LED illumination.",
    category: "equipos",
    image: "/products/equip-004.jpg",
    featured: false,
    tags: ["pieza de mano", "alta velocidad"],
  },

  // Radiologia (4)
  {
    id: "rad-001",
    nameEs: "Sensor Digital Intraoral",
    nameEn: "Intraoral Digital Sensor",
    descriptionEs: "Sensor digital intraoral tama\u00f1o 2. Alta resoluci\u00f3n, compatible con software est\u00e1ndar.",
    descriptionEn: "Size 2 intraoral digital sensor. High resolution, compatible with standard software.",
    category: "radiologia",
    image: "/products/rad-001.jpg",
    featured: false,
    tags: ["sensor", "digital"],
  },
  {
    id: "rad-002",
    nameEs: "Equipo de Rayos X Port\u00e1til",
    nameEn: "Portable X-Ray Unit",
    descriptionEs: "Equipo de rayos X dental port\u00e1til. Ligero, ergon\u00f3mico y de alta resoluci\u00f3n.",
    descriptionEn: "Portable dental X-ray unit. Lightweight, ergonomic and high resolution.",
    category: "radiologia",
    image: "/products/rad-002.jpg",
    featured: false,
    tags: ["rayos x", "port\u00e1til"],
  },
  {
    id: "rad-003",
    nameEs: "Pel\u00edculas Radiogr\u00e1ficas Periapicales x150",
    nameEn: "Periapical Radiographic Films x150",
    descriptionEs: "Pel\u00edculas radiogr\u00e1ficas periapicales de alta sensibilidad. Caja de 150 unidades.",
    descriptionEn: "High-sensitivity periapical radiographic films. Box of 150 units.",
    category: "radiologia",
    image: "/products/rad-003.jpg",
    featured: false,
    tags: ["pel\u00edculas", "radiograf\u00eda"],
  },
  {
    id: "rad-004",
    nameEs: "Delantal Plomado con Protector de Tiroides",
    nameEn: "Lead Apron with Thyroid Shield",
    descriptionEs: "Delantal plomado de 0.5mm Pb con protector de tiroides. Ligero y c\u00f3modo.",
    descriptionEn: "0.5mm Pb lead apron with thyroid shield. Lightweight and comfortable.",
    category: "radiologia",
    image: "/products/rad-004.jpg",
    featured: false,
    tags: ["delantal", "protecci\u00f3n"],
  },

  // Protesis Dental (4)
  {
    id: "prot-001",
    nameEs: "Acr\u00edlico Autocurable Rosado",
    nameEn: "Pink Self-Cure Acrylic",
    descriptionEs: "Acr\u00edlico autocurable rosado para bases de pr\u00f3tesis. Kit polvo + l\u00edquido.",
    descriptionEn: "Pink self-cure acrylic for prosthesis bases. Powder + liquid kit.",
    category: "protesis",
    image: "/products/prot-001.jpg",
    featured: false,
    tags: ["acr\u00edlico", "pr\u00f3tesis"],
  },
  {
    id: "prot-002",
    nameEs: "Material de Impresi\u00f3n Silicona",
    nameEn: "Silicone Impression Material",
    descriptionEs: "Silicona de adici\u00f3n para impresiones de alta precisi\u00f3n. Kit base + catalizador.",
    descriptionEn: "Addition silicone for high-precision impressions. Base + catalyst kit.",
    category: "protesis",
    image: "/products/prot-002.jpg",
    featured: false,
    tags: ["impresi\u00f3n", "silicona"],
  },
  {
    id: "prot-003",
    nameEs: "Dientes Artificiales Acr\u00edlicos (juego completo)",
    nameEn: "Acrylic Artificial Teeth (complete set)",
    descriptionEs: "Juego completo de dientes acr\u00edlicos de 3 capas. 28 dientes, color A2.",
    descriptionEn: "Complete set of 3-layer acrylic teeth. 28 teeth, shade A2.",
    category: "protesis",
    image: "/products/prot-003.jpg",
    featured: false,
    tags: ["dientes", "acr\u00edlico"],
  },
  {
    id: "prot-004",
    nameEs: "Articulador Semi-Ajustable",
    nameEn: "Semi-Adjustable Articulator",
    descriptionEs: "Articulador semi-ajustable tipo Arcon con arco facial. Precisi\u00f3n profesional.",
    descriptionEn: "Arcon-type semi-adjustable articulator with facebow. Professional precision.",
    category: "protesis",
    image: "/products/prot-004.jpg",
    featured: false,
    tags: ["articulador", "laboratorio"],
  },

  // Blanqueamiento Dental (4)
  {
    id: "blanq-001",
    nameEs: "Gel de Blanqueamiento Per\u00f3xido 35%",
    nameEn: "35% Peroxide Whitening Gel",
    descriptionEs: "Gel de per\u00f3xido de hidr\u00f3geno al 35% para blanqueamiento en consultorio. Kit de 3 jeringas.",
    descriptionEn: "35% hydrogen peroxide gel for in-office whitening. Kit of 3 syringes.",
    category: "blanqueamiento",
    image: "/products/blanq-001.jpg",
    featured: false,
    tags: ["blanqueamiento", "per\u00f3xido"],
  },
  {
    id: "blanq-002",
    nameEs: "Kit de Blanqueamiento Domiciliario",
    nameEn: "Home Whitening Kit",
    descriptionEs: "Kit de blanqueamiento para uso domiciliario con cubetas termoformables y gel al 16%.",
    descriptionEn: "Home whitening kit with thermoformed trays and 16% gel.",
    category: "blanqueamiento",
    image: "/products/blanq-002.jpg",
    featured: false,
    tags: ["blanqueamiento", "domiciliario"],
  },
  {
    id: "blanq-003",
    nameEs: "Barrera Gingival Fotocurable",
    nameEn: "Light-Cure Gingival Barrier",
    descriptionEs: "Barrera gingival fotocurable para protecci\u00f3n durante blanqueamiento en consultorio.",
    descriptionEn: "Light-cure gingival barrier for protection during in-office whitening.",
    category: "blanqueamiento",
    image: "/products/blanq-003.jpg",
    featured: false,
    tags: ["barrera", "protecci\u00f3n"],
  },
  {
    id: "blanq-004",
    nameEs: "Desensibilizante Post-Blanqueamiento",
    nameEn: "Post-Whitening Desensitizer",
    descriptionEs: "Gel desensibilizante con nitrato de potasio y fl\u00faor para aplicar despu\u00e9s del blanqueamiento.",
    descriptionEn: "Desensitizing gel with potassium nitrate and fluoride for post-whitening application.",
    category: "blanqueamiento",
    image: "/products/blanq-004.jpg",
    featured: false,
    tags: ["desensibilizante", "post-blanqueamiento"],
  },

  // Instrumental General (4)
  {
    id: "inst-001",
    nameEs: "Espejo Dental #5 con Mango",
    nameEn: "Dental Mirror #5 with Handle",
    descriptionEs: "Espejo dental de acero inoxidable con mango ergon\u00f3mico. Ideal para examen cl\u00ednico.",
    descriptionEn: "Stainless steel dental mirror with ergonomic handle. Ideal for clinical examination.",
    category: "instrumental",
    image: "/products/inst-001.jpg",
    featured: false,
    tags: ["espejo", "diagn\u00f3stico"],
  },
  {
    id: "inst-002",
    nameEs: "Explorador Dental Doble Punta",
    nameEn: "Double-Ended Dental Explorer",
    descriptionEs: "Explorador de doble punta para detecci\u00f3n de caries y examen de superficies.",
    descriptionEn: "Double-ended explorer for caries detection and surface examination.",
    category: "instrumental",
    image: "/products/inst-002.jpg",
    featured: false,
    tags: ["explorador", "diagn\u00f3stico"],
  },
  {
    id: "inst-003",
    nameEs: "Pinza Algodonera Premium",
    nameEn: "Premium Cotton Plier",
    descriptionEs: "Pinza algodonera de acero inoxidable con puntas estriadas para mejor agarre.",
    descriptionEn: "Stainless steel cotton plier with serrated tips for better grip.",
    category: "instrumental",
    image: "/products/inst-003.jpg",
    featured: false,
    tags: ["pinza", "algod\u00f3n"],
  },
  {
    id: "inst-004",
    nameEs: "Esp\u00e1tula para Cementos #24",
    nameEn: "Cement Spatula #24",
    descriptionEs: "Esp\u00e1tula de acero inoxidable para mezcla de cementos y materiales dentales.",
    descriptionEn: "Stainless steel spatula for mixing cements and dental materials.",
    category: "instrumental",
    image: "/products/inst-004.jpg",
    featured: false,
    tags: ["esp\u00e1tula", "mezcla"],
  },
];
